Add two articles with Rstudio/Github/Git tutorials
NorwegianVeterinaryInstitute/nvi-documentation pull request #36
Opened 2023-10-12 11:06 UTC by novica

2023-10-18 08:24 UTC, novica commented
I updated the text following your comments.

@hkaspersen woudl you be willing to check out the git part?

2023-10-19 12:45 UTC, hkaspersen commented on docs/source/tutorials/rstudio_github.md
> +All done!
Perhaps add a section describing how to use git outside Rstudio? I usually don't use the Rstudio IDE for git stuff, I only use Git Bash. Not perhaps strictly necessary for this tutorial, but might be useful as an alternative!

2023-10-19 12:45 UTC, hkaspersen requested changes
Would be nice with a small section for git outside Rstudio

2023-10-19 12:54 UTC, novica commented
> This looks great! Would be nice with a small section for git outside Rstudio as an alternative though, but otherwise this is good.

I thinik a separate article for git will make much more sense than having in in a Rstudio related one.  I can do that in the coming days.

2023-10-20 07:17 UTC, hkaspersen approved these changes

2023-10-23 18:36 UTC, merged