small typos, added TOC, correction jumbling link
NorwegianVeterinaryInstitute/nvi-documentation pull request #51
Opened 2024-02-26 15:10 UTC by evezeyl

This seems to present ok.
The filtering of variant is actually the step that is detailed - where thought to present file. Maybe we should move that up ?

2024-03-11 13:49 UTC, Thomieh73 commented on docs/source/tutorials/bcftools.md
>  ### Ressources
One s to much in "Resources"

2024-03-11 13:57 UTC, Thomieh73 commented on docs/source/tutorials/bcftools.md
> +Because in theory those sequences should be identical (obtained by the same means, but it might have been some headers reformating), we can concatenate "our" consensus and Snippy consensus and preten
type in the word " alingnment", remove first "n"

2024-03-11 13:58 UTC, Thomieh73 requested changes
Hi @evezeyl , I just found a few little typo's. Change those and then finish this request

2024-04-22 13:08 UTC, evezeyl commented on docs/source/tutorials/bcftools.md
> +Bcftools offers a variety of commands/modules to manipulate VCF files. Combining those in different way,
test

2024-04-22 13:16 UTC, evezeyl commented on docs/source/tutorials/bcftools.md
> +It can also work working with haplotypes, determine consequences of variations (eg Frame shift), and in association to specific mutation annotations (eg. as with [SnpEff]) as done in [Snippy] then it
for me the then does not fit ... otherwise working removed

2024-04-22 13:16 UTC, evezeyl commented on docs/source/tutorials/bcftools.md
>  ### Ressources
ok

2024-04-22 13:39 UTC, evezeyl commented
Damned ... did not want to ask 2 reviewers @Thomieh73 you do not need - I updated and re-read fast. Answered, and fixed layout. I think we can merge - although this tutorial can be continued but be in place already as is

2024-07-02 06:29 UTC, merged